name: "FTC"
description: ""

url: "http://ftc.iliterobotics.org/"

paginate: 10

markdown: kramdown
permalink: pretty
pygments: true
encoding: utf-8

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- compass
